site_name: Website
site_url: https://rolua-visual-scripting.github.io/RoLua-Visual-Scripting/
repo_name: RoLua-Visual-Scripting/RoLua-Visual-Scripting
repo_url: https://github.com/RoLua-Visual-Scripting/RoLua-Visual-Scripting/
theme:
  name: material
  palette:
    primary: "Deep Purple"
    accent: "Deep Purple"
  
nav:
  - Home: index.md
    
markdown_extensions:
  - admonition
  - codehilite
